server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchsize: 1048576 # 1MB, giúp gộp log thành batch lớn hơn
    batchwait: 5s # Chờ tối đa 5s trước khi gửi batch

scrape_configs:
  - job_name: user-service-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: "user-service"
          __path__: /var/log/user-service/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            operation: operation
            operationType: operationType
            latency: latency
            errorCount: errorCount
            status: status
            time: time
            message: message
      - timestamp:
          source: time
          format: RFC3339
      - labels:
          level:
          status:
          operationType:

  - job_name: collab-service-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: "collab-service"
          __path__: /var/log/collab-service/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            method: method
            path: path
            status: status
            latency: latency
            time: time
            message: message
      - timestamp:
          source: time
          format: RFC3339
      - labels:
          level:
          status:
          method:
          path:
