name: CI - Seta Exercise

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go dependencies for collab-service
        working-directory: ./collab-service
        run: go mod download

      - name: Install Go dependencies for user-service
        working-directory: ./user-service
        run: go mod download

      - name: Install Go dependencies for collab-consumer
        working-directory: ./collab-consumer
        run: go mod download

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and start Docker Compose services
        run: |
          docker-compose -f docker-compose.app.yml build
          docker-compose -f docker-compose.app.yml up -d

      - name: Wait for Postgres
        run: |
          until docker exec postgres pg_isready -U postgres; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Wait for Redis
        run: |
          until docker exec redis redis-cli ping | grep PONG; do
            echo "Waiting for Redis..."
            sleep 2
          done

      - name: Wait for Zookeeper
        run: |
          until docker exec zookeeper nc -z localhost 2181; do
          echo "Waiting for Zookeeper..."
          sleep 2
            done

      - name: Wait for Kafka
        run: |
          until docker exec kafka kafka-topics --bootstrap-server kafka:29092 --list; do
          echo "Waiting for Kafka..."
          sleep 5
            done

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.app.yml down -v

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and Push Docker images
        run: |
          docker tag collab-service:latest ${{ secrets.DOCKER_HUB_USERNAME }}/collab-service:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/collab-service:latest

          docker tag user-service:latest ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest

          docker tag collab-consumer:latest ${{ secrets.DOCKER_HUB_USERNAME }}/collab-consumer:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/collab-consumer:latest
